name: XCoordinates
version: 1.0
main: org.coleski123.xcoordinates.XCoordinates
api-version: '1.21'
description: Show your coordinates above your hotbar
author: Coleski123
website: https://discord.gg/aQz5sk6CMN
commands:
  xcoordinates:
    description: Toggle coordinates display
    usage: /<command> <enable|disable>
permissions:
  xcoordinates.use:
    description: Allows the player to use the /xcoordinates command.
    default: op
